<?php
session_start();
require_once '../config/db.php';
require_once '../includes/functions.php';
require_once '../TCPDF-main/TCPDF-main/tcpdf.php';

// Check if teacher is logged in
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'teacher') {
    header("Location: ../index.php");
    exit;
}

$current_school_id = require_school_auth();

$teacher_id = $_SESSION['user_id'];
$teacher_name = $_SESSION['full_name'];

// Get export parameters
$export_type = $_GET['type'] ?? 'full'; // full, summary, analytics
$class_filter = $_GET['class_id'] ?? null;
$term_filter = $_GET['term'] ?? null;

// Fetch school profile
$stmt = $pdo->prepare("SELECT * FROM school_profile WHERE school_id = ? LIMIT 1");
$stmt->execute([$current_school_id]);
$school = $stmt->fetch(PDO::FETCH_ASSOC);

// Build query based on filters
$where = ["e.teacher_id = ?", "e.school_id = ?", "s.school_id = ?", "c.school_id = ?"];
$params = [$teacher_id, $current_school_id, $current_school_id, $current_school_id];

if ($class_filter) {
    $where[] = "e.class_id = ?";
    $params[] = $class_filter;
}

if ($term_filter) {
    $where[] = "e.term = ?";
    $params[] = $term_filter;
}

$whereClause = "WHERE " . implode(" AND ", $where);

// Fetch evaluations with filters
$stmt = $pdo->prepare("
    SELECT e.*, s.full_name, s.class_id, s.admission_no, c.class_name
    FROM evaluations e
    JOIN students s ON e.student_id = s.id AND s.school_id = ?
    JOIN classes c ON e.class_id = c.id AND c.school_id = ?
    $whereClause
    ORDER BY c.class_name, s.full_name, e.term DESC, e.academic_year DESC
");
$stmt->execute(array_merge([$current_school_id, $current_school_id], $params));
$evaluations = $stmt->fetchAll();

// Calculate comprehensive statistics
$stats = calculateEvaluationStats($evaluations);

// Extend TCPDF class for custom export
class EvaluationExportPDF extends TCPDF {

    private $school;
    private $teacher_name;
    private $export_type;
    private $stats;

    public function __construct($school, $teacher_name, $export_type, $stats) {
        parent::__construct();
        $this->school = $school;
        $this->teacher_name = $teacher_name;
        $this->export_type = $export_type;
        $this->stats = $stats;
    }

    // Page header
    public function Header() {
        // School logo
        if (!empty($this->school['school_logo']) && file_exists('../' . $this->school['school_logo'])) {
            $this->Image('../' . $this->school['school_logo'], 15, 10, 20, 20, '', '', '', false, 300, '', false, false, 0);
        }

        // School name and export info
        $this->SetFont('helvetica', 'B', 14);
        $this->SetXY(40, 12);
        $this->Cell(0, 6, strtoupper($this->school['school_name']), 0, 1, 'L');

        $this->SetFont('helvetica', '', 9);
        $this->SetXY(40, 18);
        $this->Cell(0, 4, 'Student Evaluations Data Export', 0, 1, 'L');

        $this->SetXY(40, 22);
        $this->Cell(0, 4, 'Generated by: ' . $this->teacher_name . ' | Date: ' . date('F j, Y'), 0, 1, 'L');

        // Decorative line
        $this->SetLineWidth(0.5);
        $this->Line(15, 30, 195, 30);

        // Export type title
        $this->SetFont('helvetica', 'B', 12);
        $this->SetXY(15, 35);
        $title = ucfirst($this->export_type) . ' Evaluation Export Report';
        $this->Cell(0, 8, $title, 0, 1, 'C');

        $this->SetY(50);
    }

    // Page footer
    public function Footer() {
        $this->SetY(-20);

        // Footer line
        $this->SetLineWidth(0.3);
        $this->Line(15, -18, 195, -18);

        // Footer text
        $this->SetFont('helvetica', 'I', 7);
        $this->SetXY(15, -15);
        $this->Cell(0, 4, 'This document contains confidential student evaluation data. Generated by SahabFormMaster System.', 0, 0, 'L');

        // Page number
        $this->SetFont('helvetica', 'I', 8);
        $this->Cell(0, 4, 'Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, 0, 'R');
    }
}

// Create PDF instance
$pdf = new EvaluationExportPDF($school, $teacher_name, $export_type, $stats);

// Set document information
$pdf->SetCreator($school['school_name'] ?? 'School');
$pdf->SetAuthor($school['school_name']);
$pdf->SetTitle('Student Evaluations Data Export - ' . $teacher_name);
$pdf->SetSubject('Comprehensive Student Evaluation Data Export');

// Set margins
$pdf->SetMargins(15, 55, 15);
$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(25);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 30);

// Add first page
$pdf->AddPage();

// Generate content based on export type
switch ($export_type) {
    case 'summary':
        generateSummaryExport($pdf, $evaluations, $stats);
        break;
    case 'analytics':
        generateAnalyticsExport($pdf, $evaluations, $stats);
        break;
    case 'full':
    default:
        generateFullExport($pdf, $evaluations, $stats);
        break;
}

function generateFullExport($pdf, $evaluations, $stats) {
    // Executive Summary
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->Cell(0, 10, 'EXECUTIVE SUMMARY', 0, 1, 'L');

    $pdf->SetFont('helvetica', '', 9);
    $summary_text = "This report contains {$stats['total_evaluations']} student evaluations across {$stats['total_students']} students and {$stats['total_classes']} classes. ";
    $summary_text .= "The evaluation period covers terms {$stats['terms_range']} in academic year {$stats['academic_year_range']}.";
    $pdf->MultiCell(0, 5, $summary_text, 0, 'L');
    $pdf->Ln(5);

    // Statistics Overview
    generateStatisticsSection($pdf, $stats);

    // Detailed Data Table
    $pdf->AddPage();
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->Cell(0, 10, 'DETAILED EVALUATION DATA', 0, 1, 'L');

    generateDataTable($pdf, $evaluations);

    // Comments Section
    generateCommentsSection($pdf, $evaluations);
}

function generateSummaryExport($pdf, $evaluations, $stats) {
    // Summary Statistics
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->Cell(0, 10, 'EVALUATION SUMMARY STATISTICS', 0, 1, 'L');

    generateStatisticsSection($pdf, $stats);

    // Class-wise Summary
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->Cell(0, 10, 'CLASS-WISE SUMMARY', 0, 1, 'L');

    generateClassSummary($pdf, $stats);

    // Performance Overview
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->Cell(0, 10, 'PERFORMANCE OVERVIEW', 0, 1, 'L');

    generatePerformanceOverview($pdf, $stats);
}

function generateAnalyticsExport($pdf, $evaluations, $stats) {
    // Analytics Header
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->Cell(0, 10, 'EVALUATION ANALYTICS & INSIGHTS', 0, 1, 'L');

    // Rating Distribution Charts (Text-based representation)
    generateRatingCharts($pdf, $stats);

    // Trend Analysis
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->Cell(0, 10, 'TREND ANALYSIS', 0, 1, 'L');

    generateTrendAnalysis($pdf, $stats);

    // Recommendations
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->Cell(0, 10, 'RECOMMENDATIONS', 0, 1, 'L');

    generateRecommendations($pdf, $stats);
}

function generateStatisticsSection($pdf, $stats) {
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->SetFillColor(240, 240, 240);

    // Main Statistics
    $statistics = [
        ['Total Evaluations', $stats['total_evaluations']],
        ['Total Students', $stats['total_students']],
        ['Total Classes', $stats['total_classes']],
        ['Academic Year Range', $stats['academic_year_range']],
        ['Terms Covered', $stats['terms_range']]
    ];

    foreach ($statistics as $stat) {
        $pdf->Cell(80, 8, $stat[0] . ':', 1, 0, 'L', true);
        $pdf->Cell(30, 8, $stat[1], 1, 1, 'C', true);
    }

    $pdf->Ln(5);

    // Rating Distribution
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->Cell(0, 8, 'RATING DISTRIBUTION BY DOMAIN', 0, 1, 'L');

    $pdf->SetFont('helvetica', '', 8);
    $pdf->SetFillColor(240, 240, 240);

    $domains = ['academic', 'non_academic', 'cognitive', 'psychomotor', 'affective'];
    $domain_names = ['Academic', 'Non-Academic', 'Cognitive', 'Psychomotor', 'Affective'];

    foreach ($domains as $i => $domain) {
        $pdf->Cell(25, 6, $domain_names[$i], 1, 0, 'L', true);
        $pdf->Cell(15, 6, 'Exc: ' . ($stats['rating_distribution'][$domain]['excellent'] ?? 0), 1, 0, 'C');
        $pdf->Cell(15, 6, 'VG: ' . ($stats['rating_distribution'][$domain]['very-good'] ?? 0), 1, 0, 'C');
        $pdf->Cell(15, 6, 'Good: ' . ($stats['rating_distribution'][$domain]['good'] ?? 0), 1, 0, 'C');
        $pdf->Cell(15, 6, 'NI: ' . ($stats['rating_distribution'][$domain]['needs-improvement'] ?? 0), 1, 1, 'C');
    }
}

function generateDataTable($pdf, $evaluations) {
    // Table headers
    $pdf->SetFont('helvetica', 'B', 7);
    $pdf->SetFillColor(59, 130, 246);
    $pdf->SetTextColor(255, 255, 255);

    $headers = ['S/N', 'Student Name', 'Class', 'Term', 'Academic', 'Non-Acad', 'Cognitive', 'Psychomotor', 'Affective'];
    $widths = [8, 35, 20, 12, 18, 18, 18, 18, 18];

    foreach ($headers as $i => $header) {
        $pdf->Cell($widths[$i], 8, $header, 1, 0, 'C', true);
    }
    $pdf->Ln();

    // Table data
    $pdf->SetFont('helvetica', '', 6);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFillColor(248, 250, 252);

    $counter = 1;
    $fill = false;

    foreach ($evaluations as $eval) {
        $pdf->SetFillColor($fill ? 248 : 255, $fill ? 250 : 255, $fill ? 252 : 255);

        $pdf->Cell(8, 6, $counter++, 1, 0, 'C', $fill);

        // Student name (truncated)
        $name = strlen($eval['full_name']) > 18 ? substr($eval['full_name'], 0, 15) . '...' : $eval['full_name'];
        $pdf->Cell(35, 6, $name, 1, 0, 'L', $fill);

        $pdf->Cell(20, 6, $eval['class_name'], 1, 0, 'L', $fill);
        $pdf->Cell(12, 6, 'T' . $eval['term'], 1, 0, 'C', $fill);

        // Rating cells with colors
        $ratings = ['academic', 'non_academic', 'cognitive', 'psychomotor', 'affective'];
        foreach ($ratings as $rating) {
            $rating_value = $eval[$rating];
            $color = getRatingColor($rating_value);

            $pdf->SetFillColor($color['r'], $color['g'], $color['b']);
            $pdf->SetTextColor(255, 255, 255);
            $pdf->Cell(18, 6, ucfirst(str_replace('-', ' ', $rating_value)), 1, 0, 'C', true);
            $pdf->SetTextColor(0, 0, 0);
            $pdf->SetFillColor($fill ? 248 : 255, $fill ? 250 : 255, $fill ? 252 : 255);
        }

        $pdf->Ln();
        $fill = !$fill;
    }
}

function generateCommentsSection($pdf, $evaluations) {
    $comments_exist = false;
    foreach ($evaluations as $eval) {
        if (!empty($eval['comments'])) {
            $comments_exist = true;
            break;
        }
    }

    if ($comments_exist) {
        $pdf->AddPage();
        $pdf->SetFont('helvetica', 'B', 11);
        $pdf->Cell(0, 10, 'TEACHER COMMENTS & RECOMMENDATIONS', 0, 1, 'L');

        $pdf->SetFont('helvetica', '', 8);
        $counter = 1;

        foreach ($evaluations as $eval) {
            if (!empty($eval['comments'])) {
                $pdf->SetFont('helvetica', 'B', 8);
                $pdf->Cell(0, 6, $counter . '. ' . $eval['full_name'] . ' (' . $eval['class_name'] . ')', 0, 1, 'L');

                $pdf->SetFont('helvetica', '', 7);
                $pdf->MultiCell(0, 4, $eval['comments'], 0, 'L');
                $pdf->Ln(2);
                $counter++;
            }
        }
    }
}

function generateClassSummary($pdf, $stats) {
    if (isset($stats['class_summary'])) {
        $pdf->SetFont('helvetica', 'B', 9);
        $pdf->SetFillColor(240, 240, 240);

        foreach ($stats['class_summary'] as $class_name => $class_stats) {
            $pdf->Cell(40, 8, $class_name, 1, 0, 'L', true);
            $pdf->Cell(20, 8, 'Students: ' . $class_stats['students'], 1, 0, 'L', true);
            $pdf->Cell(30, 8, 'Evaluations: ' . $class_stats['evaluations'], 1, 0, 'L', true);
            $pdf->Cell(40, 8, 'Avg Rating: ' . number_format($class_stats['avg_rating'], 1), 1, 1, 'L', true);
        }
    }
}

function generatePerformanceOverview($pdf, $stats) {
    $pdf->SetFont('helvetica', '', 9);

    $overview = "• Total evaluations conducted: {$stats['total_evaluations']}\n";
    $overview .= "• Students evaluated: {$stats['total_students']}\n";
    $overview .= "• Classes covered: {$stats['total_classes']}\n";

    if ($stats['top_performing_domain']) {
        $overview .= "• Top performing domain: " . ucfirst($stats['top_performing_domain']) . "\n";
    }

    if ($stats['needs_improvement_domain']) {
        $overview .= "• Domain needing attention: " . ucfirst($stats['needs_improvement_domain']) . "\n";
    }

    $pdf->MultiCell(0, 5, $overview, 0, 'L');
}

function generateRatingCharts($pdf, $stats) {
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->Cell(0, 10, 'RATING DISTRIBUTION CHARTS', 0, 1, 'L');

    // Simple text-based bar charts
    $domains = ['academic', 'non_academic', 'cognitive', 'psychomotor', 'affective'];
    $domain_names = ['Academic Performance', 'Non-Academic Activities', 'Cognitive Domain', 'Psychomotor Domain', 'Affective Domain'];

    foreach ($domains as $i => $domain) {
        $pdf->SetFont('helvetica', 'B', 9);
        $pdf->Cell(0, 8, $domain_names[$i], 0, 1, 'L');

        $pdf->SetFont('helvetica', '', 8);
        $ratings = ['excellent', 'very-good', 'good', 'needs-improvement'];
        $rating_names = ['Excellent', 'Very Good', 'Good', 'Needs Improvement'];

        foreach ($ratings as $j => $rating) {
            $count = $stats['rating_distribution'][$domain][$rating] ?? 0;
            $percentage = $stats['total_evaluations'] > 0 ? ($count / $stats['total_evaluations']) * 100 : 0;

            $pdf->Cell(30, 6, $rating_names[$j] . ':', 0, 0, 'L');
            $pdf->Cell(15, 6, $count, 0, 0, 'C');
            $pdf->Cell(20, 6, number_format($percentage, 1) . '%', 0, 0, 'R');

            // Simple bar representation
            $bar_length = min($percentage * 2, 50); // Max 50 units
            $pdf->Cell($bar_length, 6, str_repeat('█', intval($bar_length / 2)), 0, 1, 'L');
        }

        $pdf->Ln(3);
    }
}

function generateTrendAnalysis($pdf, $stats) {
    $pdf->SetFont('helvetica', '', 9);

    $analysis = "Based on the evaluation data:\n\n";

    if (isset($stats['rating_distribution'])) {
        $excellent_total = 0;
        $needs_improvement_total = 0;

        foreach ($stats['rating_distribution'] as $domain => $ratings) {
            $excellent_total += $ratings['excellent'] ?? 0;
            $needs_improvement_total += $ratings['needs-improvement'] ?? 0;
        }

        $excellent_percentage = $stats['total_evaluations'] > 0 ? ($excellent_total / ($stats['total_evaluations'] * 5)) * 100 : 0;
        $needs_improvement_percentage = $stats['total_evaluations'] > 0 ? ($needs_improvement_total / ($stats['total_evaluations'] * 5)) * 100 : 0;

        $analysis .= "• {$excellent_percentage}% of all ratings are 'Excellent'\n";
        $analysis .= "• {$needs_improvement_percentage}% of ratings indicate 'Needs Improvement'\n";
        $analysis .= "• Overall performance trend: " . ($excellent_percentage > $needs_improvement_percentage ? 'Positive' : 'Needs Attention') . "\n";
    }

    $pdf->MultiCell(0, 5, $analysis, 0, 'L');
}

function generateRecommendations($pdf, $stats) {
    $pdf->SetFont('helvetica', '', 9);

    $recommendations = "Based on the evaluation analysis, the following recommendations are suggested:\n\n";

    if (isset($stats['needs_improvement_domain'])) {
        $recommendations .= "• Focus improvement efforts on: " . ucfirst($stats['needs_improvement_domain']) . "\n";
    }

    if (isset($stats['top_performing_domain'])) {
        $recommendations .= "• Continue strengthening: " . ucfirst($stats['top_performing_domain']) . "\n";
    }

    $recommendations .= "• Regular evaluation monitoring and feedback sessions\n";
    $recommendations .= "• Professional development for teachers in identified weak areas\n";
    $recommendations .= "• Parent-teacher conferences to discuss evaluation results\n";

    $pdf->MultiCell(0, 5, $recommendations, 0, 'L');
}

// Helper function to calculate comprehensive statistics
function calculateEvaluationStats($evaluations) {
    $stats = [
        'total_evaluations' => count($evaluations),
        'total_students' => count(array_unique(array_column($evaluations, 'student_id'))),
        'total_classes' => count(array_unique(array_column($evaluations, 'class_name'))),
        'rating_distribution' => [],
        'class_summary' => [],
        'terms_range' => '',
        'academic_year_range' => ''
    ];

    // Get terms and academic years range
    $terms = array_unique(array_column($evaluations, 'term'));
    $academic_years = array_unique(array_column($evaluations, 'academic_year'));

    sort($terms);
    sort($academic_years);

    $stats['terms_range'] = implode(', ', $terms);
    $stats['academic_year_range'] = implode(', ', $academic_years);

    // Calculate rating distribution
    $domains = ['academic', 'non_academic', 'cognitive', 'psychomotor', 'affective'];
    $ratings = ['excellent', 'very-good', 'good', 'needs-improvement'];

    foreach ($domains as $domain) {
        $stats['rating_distribution'][$domain] = array_fill_keys($ratings, 0);
    }

    foreach ($evaluations as $eval) {
        foreach ($domains as $domain) {
            $rating = $eval[$domain];
            if (isset($stats['rating_distribution'][$domain][$rating])) {
                $stats['rating_distribution'][$domain][$rating]++;
            }
        }

        // Class summary
        $class_name = $eval['class_name'];
        if (!isset($stats['class_summary'][$class_name])) {
            $stats['class_summary'][$class_name] = [
                'students' => 0,
                'evaluations' => 0,
                'total_rating' => 0
            ];
        }

        $stats['class_summary'][$class_name]['evaluations']++;

        // Calculate average rating for this evaluation
        $rating_sum = 0;
        $rating_count = 0;
        foreach ($domains as $domain) {
            $rating_value = getRatingScore($eval[$domain]);
            $rating_sum += $rating_value;
            $rating_count++;
        }

        if ($rating_count > 0) {
            $avg_rating = $rating_sum / $rating_count;
            $stats['class_summary'][$class_name]['total_rating'] += $avg_rating;
        }
    }

    // Calculate averages for class summary
    foreach ($stats['class_summary'] as $class_name => &$class_stats) {
        $class_stats['students'] = count(array_unique(array_column(
            array_filter($evaluations, function($e) use ($class_name) {
                return $e['class_name'] === $class_name;
            }),
            'student_id'
        )));

        if ($class_stats['evaluations'] > 0) {
            $class_stats['avg_rating'] = $class_stats['total_rating'] / $class_stats['evaluations'];
        }
    }

    // Find top performing and needs improvement domains
    $domain_scores = [];
    foreach ($domains as $domain) {
        $excellent_count = $stats['rating_distribution'][$domain]['excellent'] ?? 0;
        $needs_improvement_count = $stats['rating_distribution'][$domain]['needs-improvement'] ?? 0;
        $domain_scores[$domain] = $excellent_count - $needs_improvement_count;
    }

    arsort($domain_scores);
    $stats['top_performing_domain'] = key($domain_scores);

    asort($domain_scores);
    $stats['needs_improvement_domain'] = key($domain_scores);

    return $stats;
}

// Helper function to get numeric score for ratings
function getRatingScore($rating) {
    switch ($rating) {
        case 'excellent': return 5;
        case 'very-good': return 4;
        case 'good': return 3;
        case 'needs-improvement': return 2;
        default: return 3;
    }
}

// Generate filename and output
$safe_teacher = preg_replace('/[^A-Za-z0-9\-_]/', '_', $teacher_name);
$safe_type = preg_replace('/[^A-Za-z0-9\-_]/', '_', $export_type);
$filename = 'Evaluation_Data_Export_' . $safe_type . '_' . $safe_teacher . '_' . date('Ymd_His') . '.pdf';

// Create directory if it doesn't exist
$export_dir = dirname(__DIR__) . '/exports/evaluations/';
if (!file_exists($export_dir)) {
    mkdir($export_dir, 0777, true);
}

$filepath = $export_dir . $filename;

// Save PDF file
$pdf->Output($filepath, 'F');

// Log the export
try {
    $stmt = $pdo->prepare("
        INSERT INTO export_logs (user_id, export_type, file_path, exported_at, ip_address)
        VALUES (?, 'evaluations_export', ?, NOW(), ?)
    ");
    $stmt->execute([
        $teacher_id,
        $filepath,
        $_SERVER['REMOTE_ADDR'] ?? 'unknown'
    ]);
} catch (PDOException $e) {
    // Silently skip logging if export_logs table doesn't exist
}

// Output PDF to browser
header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename="' . $filename . '"');
header('Content-Transfer-Encoding: binary');
header('Accept-Ranges: bytes');
header('Cache-Control: private');
readfile($filepath);
exit;

// Helper function to get rating colors for PDF
function getRatingColor($rating) {
    switch ($rating) {
        case 'excellent':
            return ['r' => 34, 'g' => 197, 'b' => 94]; // Green
        case 'very-good':
            return ['r' => 245, 'g' => 158, 'b' => 11]; // Yellow
        case 'good':
            return ['r' => 168, 'g' => 85, 'b' => 247]; // Purple
        case 'needs-improvement':
            return ['r' => 239, 'g' => 68, 'b' => 68]; // Red
        default:
            return ['r' => 156, 'g' => 163, 'b' => 175]; // Gray
    }
}
?>
