<?php
session_start();
require_once '../config/db.php';
require_once '../TCPDF-main/TCPDF-main/tcpdf.php';

// Validate principal access
if (!isset($_SESSION['user_id']) || strtolower($_SESSION['role'] ?? '') !== 'principal') {
    die("Access denied. Principal access required.");
}

// Validate POST data
$class_id = $_POST['class_id'] ?? null;
$export_type = $_POST['export_type'] ?? 'full'; // full, summary
$orientation = $_POST['orientation'] ?? 'P'; // P=Portrait, L=Landscape
$include_photos = isset($_POST['include_photos']) && $_POST['include_photos'] === '1';

if (!$class_id) {
    die("Class ID required.");
}

// Fetch class information
$class_stmt = $pdo->prepare("SELECT * FROM classes WHERE id = ?");
$class_stmt->execute([$class_id]);
$class = $class_stmt->fetch(PDO::FETCH_ASSOC);

if (!$class) {
    die("Class not found.");
}

// Fetch students for the class
$students_query = "
    SELECT s.*
    FROM students s
    WHERE s.class_id = ?
    ORDER BY s.full_name ASC
";

$students_stmt = $pdo->prepare($students_query);
$students_stmt->execute([$class_id]);
$students = $students_stmt->fetchAll(PDO::FETCH_ASSOC);

// Get school info
$school = $pdo->query("SELECT * FROM school_profile WHERE id = 1")->fetch();

// Extend TCPDF class for custom student list
class StudentListPDF extends TCPDF {

    private $school;
    private $class;
    private $export_type;
    private $include_photos;
    private $students = [];

    public function __construct($school, $class, $export_type, $include_photos) {
        parent::__construct();
        $this->school = $school;
        $this->class = $class;
        $this->export_type = $export_type;
        $this->include_photos = $include_photos;
    }

    // Page header
    public function Header() {
        // School logo
        if (!empty($this->school['school_logo']) && file_exists('../' . $this->school['school_logo'])) {
            $this->Image('../' . $this->school['school_logo'], 15, 10, 20, 20, '', '', '', false, 300, '', false, false, 0);
        }

        // School name and address
        $this->SetFont('helvetica', 'B', 14);
        $this->SetXY(40, 12);
        $this->Cell(0, 6, strtoupper($this->school['school_name']), 0, 1, 'L');

        $this->SetFont('helvetica', 'I', 10);
        $this->SetXY(40, 18);
        $this->Cell(0, 5, $this->school['school_motto'], 0, 1, 'L');

        $this->SetFont('helvetica', '', 8);
        $this->SetXY(40, 23);
        $this->Cell(0, 4, $this->school['school_address'], 0, 1, 'L');

        // Contact info
        $this->SetXY(40, 27);
        $contact = [];
        if (!empty($this->school['school_phone'])) $contact[] = 'Tel: ' . $this->school['school_phone'];
        if (!empty($this->school['school_email'])) $contact[] = 'Email: ' . $this->school['school_email'];
        $this->Cell(0, 4, implode(' | ', $contact), 0, 1, 'L');

        // Decorative line
        $this->SetLineWidth(0.5);
        $this->Line(15, 35, $this->getPageWidth() - 15, 35);

        // Report title
        $this->SetFont('helvetica', 'B', 12);
        $this->SetXY(15, 40);
        $title = $this->class['class_name'] . ' - STUDENT LIST';
        $this->Cell(0, 8, $title, 0, 1, 'C');

        // Report details
        $this->SetFont('helvetica', '', 9);
        $this->SetXY(15, 48);
        $this->Cell(60, 5, 'Class: ' . $this->class['class_name'], 0, 0, 'L');
        $this->Cell(60, 5, 'Total Students: ' . count($this->students), 0, 0, 'C');
        $this->Cell(60, 5, 'Generated: ' . date('d/m/Y H:i'), 0, 1, 'R');

        $this->SetY(65);
    }

    // Page footer
    public function Footer() {
        $this->SetY(-20);

        // Footer info
        $this->SetFont('helvetica', '', 8);
        $this->SetXY(15, -17);
        $this->Cell(80, 4, 'Generated by: SahabFormMaster School Management System', 0, 0, 'L');
        $this->Cell(80, 4, 'Principal: ' . ($_SESSION['full_name'] ?? 'Unknown'), 0, 0, 'C');
        $this->Cell(20, 4, 'Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, 1, 'R');

        // Signature line
        $this->SetXY(15, -12);
        $this->Cell(80, 4, '_______________________________', 0, 0, 'C');
        $this->Cell(80, 4, '_______________________________', 0, 1, 'C');

        $this->SetXY(15, -8);
        $this->Cell(80, 4, 'Principal/Administrator', 0, 0, 'C');
        $this->Cell(80, 4, 'Date', 0, 1, 'C');

        // Terms
        $this->SetXY(15, -4);
        $this->SetFont('helvetica', 'I', 6);
        $this->Cell(0, 3, 'This is a computer-generated report. Keep this document for official records.', 0, 1, 'C');
    }

    public function setStudents($students) {
        $this->students = $students;
    }
}

// Create PDF instance
$pdf = new StudentListPDF($school, $class, $export_type, $include_photos);
$pdf->setStudents($students);

// Set document information
$pdf->SetCreator('SahabFormMaster School Management System');
$pdf->SetAuthor($school['school_name']);
$pdf->SetTitle($class['class_name'] . ' - Student List');
$pdf->SetSubject('Student list for ' . $class['class_name']);

// Set orientation and margins
if ($orientation === 'L') {
    $pdf->AddPage('L'); // Landscape
    $pdf->SetMargins(10, 65, 10);
} else {
    $pdf->AddPage('P'); // Portrait
    $pdf->SetMargins(15, 65, 15);
}

$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(25);
$pdf->SetAutoPageBreak(TRUE, 25);

// Set font
$pdf->SetFont('helvetica', '', 8);

// Table headers
if ($export_type === 'full') {
    if ($include_photos && $orientation === 'L') {
        // Landscape with photos
        $pdf->SetFont('helvetica', 'B', 9);
        $pdf->SetFillColor(240, 240, 240);

        $pdf->Cell(25, 10, 'Photo', 1, 0, 'C', 1);
        $pdf->Cell(30, 10, 'Admission No', 1, 0, 'C', 1);
        $pdf->Cell(50, 10, 'Student Name', 1, 0, 'C', 1);
        $pdf->Cell(20, 10, 'Gender', 1, 0, 'C', 1);
        $pdf->Cell(25, 10, 'Phone', 1, 0, 'C', 1);
        $pdf->Cell(50, 10, 'Guardian', 1, 0, 'C', 1);
        $pdf->Cell(25, 10, 'Guardian Phone', 1, 1, 'C', 1);
    } else {
        // Portrait or without photos
        $pdf->SetFont('helvetica', 'B', 9);
        $pdf->SetFillColor(240, 240, 240);

        $pdf->Cell(25, 10, 'Admission No', 1, 0, 'C', 1);
        $pdf->Cell(50, 10, 'Student Name', 1, 0, 'C', 1);
        $pdf->Cell(15, 10, 'Gender', 1, 0, 'C', 1);
        $pdf->Cell(25, 10, 'Phone', 1, 0, 'C', 1);
        $pdf->Cell(40, 10, 'Guardian', 1, 0, 'C', 1);
        $pdf->Cell(30, 10, 'Guardian Phone', 1, 1, 'C', 1);
    }
} else {
    // Summary view
    $pdf->SetFont('helvetica', 'B', 9);
    $pdf->SetFillColor(240, 240, 240);

    $pdf->Cell(15, 10, 'S.No', 1, 0, 'C', 1);
    $pdf->Cell(30, 10, 'Admission No', 1, 0, 'C', 1);
    $pdf->Cell(60, 10, 'Student Name', 1, 0, 'C', 1);
    $pdf->Cell(20, 10, 'Gender', 1, 0, 'C', 1);
    $pdf->Cell(35, 10, 'Guardian Contact', 1, 1, 'C', 1);
}

// Table data
$pdf->SetFont('helvetica', '', 8);
$serial = 1;

foreach ($students as $student) {
    if ($export_type === 'full') {
        if ($include_photos && $orientation === 'L' && !empty($student['passport_photo']) && file_exists('../' . $student['passport_photo'])) {
            // Landscape with photos
            $pdf->Cell(25, 20, '', 1, 0, 'C');
            // Add photo
            $photo_path = '../' . $student['passport_photo'];
            if (file_exists($photo_path)) {
                $pdf->Image($photo_path, $pdf->GetX() - 22, $pdf->GetY() + 2, 16, 16, '', '', '', false, 300, '', false, false, 0);
            }
            $pdf->SetXY($pdf->GetX() + 25, $pdf->GetY());

            $pdf->Cell(30, 20, $student['admission_no'], 1, 0, 'C');
            $pdf->Cell(50, 20, $student['full_name'], 1, 0, 'L');
            $pdf->Cell(20, 20, $student['gender'] ?? 'N/A', 1, 0, 'C');
            $pdf->Cell(25, 20, $student['phone'] ?? 'N/A', 1, 0, 'C');
            $pdf->Cell(50, 20, $student['guardian_name'] ?? 'N/A', 1, 0, 'L');
            $pdf->Cell(25, 20, $student['guardian_phone'] ?? 'N/A', 1, 1, 'C');
        } else {
            // Portrait or without photos
            $pdf->Cell(25, 12, $student['admission_no'], 1, 0, 'C');
            $pdf->Cell(50, 12, $student['full_name'], 1, 0, 'L');
            $pdf->Cell(15, 12, $student['gender'] ?? 'N/A', 1, 0, 'C');
            $pdf->Cell(25, 12, $student['phone'] ?? 'N/A', 1, 0, 'C');
            $pdf->Cell(40, 12, $student['guardian_name'] ?? 'N/A', 1, 0, 'L');
            $pdf->Cell(30, 12, $student['guardian_phone'] ?? 'N/A', 1, 1, 'C');
        }
    } else {
        // Summary view
        $pdf->Cell(15, 10, $serial++, 1, 0, 'C');
        $pdf->Cell(30, 10, $student['admission_no'], 1, 0, 'C');
        $pdf->Cell(60, 10, $student['full_name'], 1, 0, 'L');
        $pdf->Cell(20, 10, $student['gender'] ?? 'N/A', 1, 0, 'C');
        $pdf->Cell(35, 10, $student['guardian_phone'] ?? 'N/A', 1, 1, 'C');
    }
}

// Generate filename and output
$filename = $class['class_name'] . '_Student_List_' . date('Ymd_His') . '.pdf';
$filepath = dirname(__DIR__) . '/exports/student_lists/' . $filename;

// Create directory if it doesn't exist
if (!file_exists('../exports/student_lists/')) {
    mkdir('../exports/student_lists/', 0777, true);
}

// Save PDF file
$pdf->Output($filepath, 'F');

// Log the export
$stmt = $pdo->prepare("
    INSERT INTO export_logs (user_id, export_type, file_path, exported_at, ip_address, metadata)
    VALUES (?, 'student_list_pdf', ?, NOW(), ?, ?)
");
$metadata = json_encode([
    'class_id' => $class_id,
    'class_name' => $class['class_name'],
    'export_type' => $export_type,
    'orientation' => $orientation,
    'include_photos' => $include_photos,
    'total_students' => count($students)
]);
$stmt->execute([
    $_SESSION['user_id'] ?? null,
    $filepath,
    $_SERVER['REMOTE_ADDR'] ?? 'unknown',
    $metadata
]);

// Output PDF to browser
header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename="' . $filename . '"');
header('Content-Transfer-Encoding: binary');
header('Accept-Ranges: bytes');
header('Cache-Control: private');
readfile($filepath);
exit;
?>
