<?php
session_start();
require_once '../config/db.php';
require_once '../TCPDF-main/TCPDF-main/tcpdf.php';

// Validate POST data
$payment_id = $_POST['payment_id'] ?? null;
$receipt_type = $_POST['receipt_type'] ?? 'standard'; // standard, installment, statement

if (!$payment_id) {
    die("Payment ID required.");
}

// Fetch payment details
$stmt = $pdo->prepare("
    SELECT sp.*, s.full_name, s.admission_no, s.phone, s.address,
           c.class_name, u.full_name as verified_by_name,
           (SELECT SUM(amount_due) FROM payment_installments WHERE payment_id = sp.id) as total_installments
    FROM student_payments sp
    JOIN students s ON sp.student_id = s.id
    JOIN classes c ON sp.class_id = c.id
    LEFT JOIN users u ON sp.verified_by = u.id
    WHERE sp.id = ?
");
$stmt->execute([$payment_id]);
$payment = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$payment) {
    die("Payment not found.");
}

// Fetch installments if any
$installments_stmt = $pdo->prepare("
    SELECT * FROM payment_installments
    WHERE payment_id = ?
    ORDER BY installment_number
");
$installments_stmt->execute([$payment_id]);
$installments = $installments_stmt->fetchAll(PDO::FETCH_ASSOC);

// Get school info
$school = $pdo->query("SELECT * FROM school_profile WHERE id = 1")->fetch();

// Calculate payment statistics
$total_paid = $payment['amount_paid'];
$balance = $payment['balance'];
$next_installment = null;

if (!empty($installments)) {
    foreach ($installments as $installment) {
        if ($installment['status'] === 'pending' && strtotime($installment['due_date']) > time()) {
            $next_installment = $installment;
            break;
        }
    }
}

// Extend TCPDF class for custom receipt
class PaymentReceiptPDF extends TCPDF {

    private $school;
    private $payment;
    private $receipt_type;

    public function __construct($school, $payment, $receipt_type) {
        parent::__construct();
        $this->school = $school;
        $this->payment = $payment;
        $this->receipt_type = $receipt_type;
    }

    // Page header
    public function Header() {
        // School logo
        if (!empty($this->school['school_logo']) && file_exists('../' . $this->school['school_logo'])) {
            $this->Image('../' . $this->school['school_logo'], 15, 10, 20, 20, '', '', '', false, 300, '', false, false, 0);
        }

        // School name and address
        $this->SetFont('helvetica', 'B', 14);
        $this->SetXY(40, 12);
        $this->Cell(0, 6, strtoupper($this->school['school_name']), 0, 1, 'L');

        $this->SetFont('helvetica', 'I', 10);
        $this->SetXY(40, 18);
        $this->Cell(0, 5, $this->school['school_motto'], 0, 1, 'L');

        $this->SetFont('helvetica', '', 8);
        $this->SetXY(40, 23);
        $this->Cell(0, 4, $this->school['school_address'], 0, 1, 'L');

        // Contact info
        $this->SetXY(40, 27);
        $contact = [];
        if (!empty($this->school['school_phone'])) $contact[] = 'Tel: ' . $this->school['school_phone'];
        if (!empty($this->school['school_email'])) $contact[] = 'Email: ' . $this->school['school_email'];
        $this->Cell(0, 4, implode(' | ', $contact), 0, 1, 'L');

        // Decorative line
        $this->SetLineWidth(0.5);
        $this->Line(15, 35, 195, 35);

        // Receipt title
        $this->SetFont('helvetica', 'B', 12);
        $this->SetXY(15, 40);
        $title = $this->receipt_type === 'statement' ? 'PAYMENT STATEMENT' : 'OFFICIAL PAYMENT RECEIPT';
        $this->Cell(0, 8, $title, 0, 1, 'C');

        $this->SetY(52);
    }

    // Page footer
    public function Footer() {
        $this->SetY(-25);

        // Receipt number and date
        $this->SetFont('helvetica', '', 8);
        $this->SetXY(15, -22);
        $this->Cell(60, 4, 'Receipt No: ' . $this->payment['receipt_number'], 0, 0, 'L');
        $this->Cell(60, 4, 'Date: ' . date('d/m/Y H:i'), 0, 0, 'C');
        $this->Cell(60, 4, 'Generated by: SahabFormMaster', 0, 1, 'R');

        // Signature lines
        $this->SetXY(15, -15);
        $this->Cell(60, 4, '_______________________________', 0, 0, 'C');
        $this->Cell(60, 4, '_______________________________', 0, 0, 'C');
        $this->Cell(60, 4, '_______________________________', 0, 1, 'C');

        $this->SetXY(15, -11);
        $this->Cell(60, 4, 'Student/Parent', 0, 0, 'C');
        $this->Cell(60, 4, 'Cashier', 0, 0, 'C');
        $this->Cell(60, 4, 'Principal', 0, 1, 'C');

        // Page number
        $this->SetFont('helvetica', 'I', 7);
        $this->Cell(0, 8, 'Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, 0, 'C');

        // Terms
        $this->SetXY(15, -6);
        $this->SetFont('helvetica', 'I', 6);
        $this->Cell(0, 3, 'This is a computer-generated receipt. Keep this receipt for your records.', 0, 1, 'C');
    }
}

// Create PDF instance
$pdf = new PaymentReceiptPDF($school, $payment, $receipt_type);

// Set document information
$pdf->SetCreator($school['school_name'] ?? 'School');
$pdf->SetAuthor($school['school_name']);
$pdf->SetTitle('Payment Receipt - ' . $payment['full_name']);
$pdf->SetSubject('Payment receipt for ' . $payment['full_name']);

// Set margins
$pdf->SetMargins(15, 60, 15); // Left, Top, Right
$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(25);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 30);

// Add first page
$pdf->AddPage();

// Student and Payment Information
$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(0, 8, 'STUDENT INFORMATION', 0, 1, 'L');

$pdf->SetFont('helvetica', '', 9);
$pdf->Cell(50, 6, 'Student Name:', 0, 0, 'L');
$pdf->Cell(0, 6, $payment['full_name'], 0, 1, 'L');

$pdf->Cell(50, 6, 'Admission Number:', 0, 0, 'L');
$pdf->Cell(0, 6, $payment['admission_no'], 0, 1, 'L');

$pdf->Cell(50, 6, 'Class:', 0, 0, 'L');
$pdf->Cell(50, 6, $payment['class_name'], 0, 0, 'L');
$pdf->Cell(30, 6, 'Term:', 0, 0, 'L');
$pdf->Cell(0, 6, $payment['term'], 0, 1, 'L');

if (!empty($payment['phone'])) {
    $pdf->Cell(50, 6, 'Phone:', 0, 0, 'L');
    $pdf->Cell(0, 6, $payment['phone'], 0, 1, 'L');
}

$pdf->Ln(5);

// Payment Details
$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(0, 8, 'PAYMENT DETAILS', 0, 1, 'L');

$pdf->SetFont('helvetica', '', 9);
$pdf->Cell(50, 6, 'Receipt Number:', 0, 0, 'L');
$pdf->SetFont('helvetica', 'B', 9);
$pdf->SetTextColor(220, 53, 69);
$pdf->Cell(0, 6, $payment['receipt_number'], 0, 1, 'L');
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 9);

$pdf->Cell(50, 6, 'Payment Date:', 0, 0, 'L');
$pdf->Cell(50, 6, date('F j, Y', strtotime($payment['payment_date'])), 0, 0, 'L');
$pdf->Cell(30, 6, 'Method:', 0, 0, 'L');
$pdf->Cell(0, 6, ucfirst(str_replace('_', ' ', $payment['payment_method'])), 0, 1, 'L');

if (!empty($payment['transaction_id'])) {
    $pdf->Cell(50, 6, 'Transaction ID:', 0, 0, 'L');
    $pdf->Cell(0, 6, $payment['transaction_id'], 0, 1, 'L');
}

if (!empty($payment['academic_year'])) {
    $pdf->Cell(50, 6, 'Academic Year:', 0, 0, 'L');
    $pdf->Cell(0, 6, $payment['academic_year'], 0, 1, 'L');
}

$pdf->Ln(5);

// Amount Information - Highlighted
$pdf->SetFillColor(240, 240, 240);
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 12, 'PAYMENT AMOUNT', 1, 1, 'C', 1);

$pdf->SetFont('helvetica', '', 10);
$pdf->Cell(60, 10, 'Total Fee Amount:', 1, 0, 'L');
$pdf->Cell(0, 10, '₦' . number_format($payment['total_amount'], 2), 1, 1, 'R');

if ($payment['amount_paid'] > 0) {
    $pdf->Cell(60, 10, 'Amount Paid:', 1, 0, 'L');
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->SetTextColor(34, 197, 94);
    $pdf->Cell(0, 10, '₦' . number_format($payment['amount_paid'], 2), 1, 1, 'R');
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFont('helvetica', '', 10);
}

if ($balance != 0) {
    $pdf->Cell(60, 10, 'Outstanding Balance:', 1, 0, 'L');
    $pdf->SetTextColor($balance > 0 ? 239, 68, 68 : 34, 197, 94);
    $pdf->Cell(0, 10, '₦' . number_format(abs($balance), 2) . ($balance > 0 ? ' (Due)' : ' (Credit)'), 1, 1, 'R');
    $pdf->SetTextColor(0, 0, 0);
}

$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(60, 12, 'Payment Status:', 1, 0, 'L');
$status_color = $payment['status'] === 'completed' ? [34, 197, 94] : [251, 191, 36];
$pdf->SetTextColor($status_color[0], $status_color[1], $status_color[2]);
$pdf->Cell(0, 12, ucfirst($payment['status']), 1, 1, 'R');
$pdf->SetTextColor(0, 0, 0);

$pdf->Ln(5);

// Installment Information (if applicable)
if ($payment['payment_type'] === 'installment' && !empty($installments)) {
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->Cell(0, 8, 'INSTALLMENT SCHEDULE', 0, 1, 'L');

    $pdf->SetFont('helvetica', 'B', 8);
    $pdf->SetFillColor(230, 230, 230);

    $pdf->Cell(15, 8, 'Inst.#', 1, 0, 'C', 1);
    $pdf->Cell(25, 8, 'Due Date', 1, 0, 'C', 1);
    $pdf->Cell(25, 8, 'Amount Due', 1, 0, 'C', 1);
    $pdf->Cell(25, 8, 'Amount Paid', 1, 0, 'C', 1);
    $pdf->Cell(20, 8, 'Status', 1, 1, 'C', 1);

    $pdf->SetFont('helvetica', '', 8);
    foreach ($installments as $installment) {
        $pdf->Cell(15, 6, $installment['installment_number'], 1, 0, 'C');
        $pdf->Cell(25, 6, date('d/m/Y', strtotime($installment['due_date'])), 1, 0, 'C');
        $pdf->Cell(25, 6, '₦' . number_format($installment['amount_due'], 2), 1, 0, 'R');
        $pdf->Cell(25, 6, $installment['amount_paid'] > 0 ? '₦' . number_format($installment['amount_paid'], 2) : '-', 1, 0, 'R');

        // Status with color
        $status_text = ucfirst($installment['status']);
        if ($installment['status'] === 'paid') {
            $pdf->SetTextColor(34, 197, 94);
        } elseif ($installment['status'] === 'overdue') {
            $pdf->SetTextColor(239, 68, 68);
        } else {
            $pdf->SetTextColor(251, 191, 36);
        }
        $pdf->Cell(20, 6, $status_text, 1, 1, 'C');
        $pdf->SetTextColor(0, 0, 0);
    }

    $pdf->Ln(5);
}

// Next Payment Information
if ($next_installment) {
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->SetFillColor(255, 243, 205);
    $pdf->Cell(0, 10, 'NEXT PAYMENT DUE', 1, 1, 'C', 1);

    $pdf->SetFont('helvetica', '', 9);
    $pdf->Cell(50, 8, 'Installment:', 0, 0, 'L');
    $pdf->Cell(0, 8, '#' . $next_installment['installment_number'], 0, 1, 'L');

    $pdf->Cell(50, 8, 'Due Date:', 0, 0, 'L');
    $pdf->Cell(0, 8, date('l, F j, Y', strtotime($next_installment['due_date'])), 0, 1, 'L');

    $pdf->Cell(50, 8, 'Amount Due:', 0, 0, 'L');
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->SetTextColor(239, 68, 68);
    $pdf->Cell(0, 8, '₦' . number_format($next_installment['amount_due'], 2), 0, 1, 'L');
    $pdf->SetTextColor(0, 0, 0);

    $pdf->Ln(5);
}

// Additional Notes
if (!empty($payment['notes'])) {
    $pdf->SetFont('helvetica', 'B', 9);
    $pdf->Cell(0, 6, 'ADDITIONAL NOTES:', 0, 1, 'L');
    $pdf->SetFont('helvetica', '', 8);
    $pdf->MultiCell(0, 5, $payment['notes'], 0, 'L');
    $pdf->Ln(3);
}

// Verification Information
if (!empty($payment['verified_by_name'])) {
    $pdf->SetFont('helvetica', 'B', 9);
    $pdf->Cell(0, 6, 'VERIFICATION:', 0, 1, 'L');
    $pdf->SetFont('helvetica', '', 8);
    $pdf->Cell(50, 5, 'Verified By:', 0, 0, 'L');
    $pdf->Cell(0, 5, $payment['verified_by_name'], 0, 1, 'L');
    $pdf->Cell(50, 5, 'Verified At:', 0, 0, 'L');
    $pdf->Cell(0, 5, (!empty($payment['verified_at'])) ? date('F j, Y H:i', strtotime($payment['verified_at'])) : 'Auto-verified', 0, 1, 'L');
}

// Important notices
$pdf->Ln(10);
$pdf->SetFont('helvetica', 'B', 9);
$pdf->Cell(0, 6, 'IMPORTANT NOTICES:', 0, 1, 'L');
$pdf->SetFont('helvetica', '', 7);
$notices = [
    "• This receipt is valid proof of payment for the specified amount.",
    "• All payments are subject to school fee policies and refund terms.",
    "• For installment payments, subsequent payments must be made by due dates.",
    "• Keep this receipt safe for future reference and verification.",
    "• Contact the school administration for any payment-related queries."
];

foreach ($notices as $notice) {
    $pdf->Cell(5, 4, '', 0, 0, 'L');
    $pdf->MultiCell(0, 4, $notice, 0, 'L');
}

// Generate filename and output
$filename = 'Receipt_' . preg_replace('/[^A-Za-z0-9\-_]/', '_', $payment['receipt_number']) . '_' . date('Ymd_His') . '.pdf';

$filepath = '../exports/receipts/' . $filename;

// Save PDF file
$pdf->Output($filepath, 'F');

// Log the export
$stmt = $pdo->prepare("
    INSERT INTO export_logs (user_id, export_type, file_path, exported_at, ip_address, metadata)
    VALUES (?, 'receipt', ?, NOW(), ?, ?)
");
$metadata = json_encode([
    'payment_id' => $payment_id,
    'receipt_number' => $payment['receipt_number'],
    'amount' => $payment['amount_paid'],
    'student' => $payment['full_name']
]);
$stmt->execute([
    $_SESSION['user_id'] ?? null,
    $filepath,
    $_SERVER['REMOTE_ADDR'] ?? 'unknown',
    $metadata
]);

// Output PDF to browser
header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename="' . $filename . '"');
header('Content-Transfer-Encoding: binary');
header('Accept-Ranges: bytes');
header('Cache-Control: private');
readfile($filepath);
exit;
?>
