<?php
session_start();
require_once '../config/db.php';
require_once '../includes/functions.php';
require_once '../includes/auth-check.php';

// Only principal/admin with school authentication
if (!isset($_SESSION['user_id']) || strtolower($_SESSION['role'] ?? '') !== 'principal') {
    header("Location: ../index.php");
    exit;
}

$current_school_id = require_school_auth();

$format = $_GET['format'] ?? 'pdf';
$search = $_GET['search'] ?? '';
$term = $_GET['term'] ?? '';
$rating = $_GET['rating'] ?? '';
$class_id = $_GET['class_id'] ?? '';

// Build WHERE clause for filtering
$where = ["e.school_id = ?"];
$params = [$current_school_id];

if (!empty($search)) {
    $where[] = "(s.full_name LIKE ? OR s.admission_no LIKE ?)";
    $params[] = "%$search%";
    $params[] = "%$search%";
}

if (!empty($term)) {
    $where[] = "e.term = ?";
    $params[] = $term;
}

if (!empty($rating)) {
    $where[] = "(e.academic = ? OR e.non_academic = ? OR e.cognitive = ? OR e.psychomotor = ? OR e.affective = ?)";
    $params = array_merge($params, array_fill(0, 5, $rating));
}

if (!empty($class_id)) {
    $where[] = "e.class_id = ?";
    $params[] = $class_id;
}

$where_clause = "WHERE " . implode(" AND ", $where);

// Fetch evaluations with filtering
$stmt = $pdo->prepare("
    SELECT e.*, s.full_name, s.class_id, s.admission_no, c.class_name
    FROM evaluations e
    JOIN students s ON e.student_id = s.id
    LEFT JOIN classes c ON e.class_id = c.id
    $where_clause
    ORDER BY e.created_at DESC
");
$stmt->execute($params);
$evaluations = $stmt->fetchAll();

// Fetch school profile
$stmt = $pdo->prepare("SELECT * FROM school_profile WHERE school_id = ? LIMIT 1");
$stmt->execute([$current_school_id]);
$school = $stmt->fetch(PDO::FETCH_ASSOC);

if ($format === 'excel') {
    exportToExcel($evaluations, $school, $search, $term, $rating, $class_id);
} else {
    exportToPDF($evaluations, $school, $search, $term, $rating, $class_id);
}

function exportToExcel($evaluations, $school, $search, $term, $rating, $class_id) {
    require_once '../vendor/autoload.php'; // Assuming PhpSpreadsheet is installed via Composer
    
    use PhpOffice\PhpSpreadsheet\Spreadsheet;
    use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();

    // Set document properties
    $spreadsheet->getProperties()
        ->setCreator($school['school_name'] ?? 'SahabFormMaster')
        ->setTitle('Student Evaluations Export')
        ->setSubject('Student Evaluations')
        ->setDescription('Exported student evaluations from SahabFormMaster');

    // Header
    $sheet->setCellValue('A1', strtoupper($school['school_name'] ?? 'SAHABFORMMASTER'));
    $sheet->setCellValue('A2', 'Student Evaluations Export Report');
    $sheet->setCellValue('A3', 'Generated on: ' . date('F j, Y'));
    $sheet->setCellValue('A4', 'Generated by: ' . ($_SESSION['full_name'] ?? 'Administrator'));

    // Filters info
    $filter_info = [];
    if ($search) $filter_info[] = "Search: $search";
    if ($term) $filter_info[] = "Term: $term";
    if ($rating) $filter_info[] = "Rating: $rating";
    if ($class_id) {
        $stmt = $pdo->prepare("SELECT class_name FROM classes WHERE id = ?");
        $stmt->execute([$class_id]);
        $class_name = $stmt->fetchColumn();
        $filter_info[] = "Class: $class_name";
    }

    $sheet->setCellValue('A5', 'Filters: ' . implode(' | ', $filter_info));

    // Column headers
    $headers = [
        'Student Name', 'Admission No', 'Class', 'Term', 'Academic Year',
        'Academic', 'Non-Academic', 'Cognitive', 'Psychomotor', 'Affective',
        'Comments', 'Date Evaluated', 'Evaluated By'
    ];

    $column = 'A';
    foreach ($headers as $header) {
        $sheet->setCellValue($column . '7', $header);
        $sheet->getStyle($column . '7')->getFont()->setBold(true);
        $sheet->getStyle($column . '7')->getFill()
            ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
            ->getStartColor()->setARGB('FFD3D3D3');
        $column++;
    }

    // Data rows
    $row = 8;
    foreach ($evaluations as $eval) {
        $sheet->setCellValue('A' . $row, $eval['full_name']);
        $sheet->setCellValue('B' . $row, $eval['admission_no']);
        $sheet->setCellValue('C' . $row, $eval['class_name'] ?? 'N/A');
        $sheet->setCellValue('D' . $row, 'Term ' . $eval['term']);
        $sheet->setCellValue('E' . $row, $eval['academic_year']);
        $sheet->setCellValue('F' . $row, ucfirst(str_replace('-', ' ', $eval['academic'])));
        $sheet->setCellValue('G' . $row, ucfirst(str_replace('-', ' ', $eval['non_academic'])));
        $sheet->setCellValue('H' . $row, ucfirst(str_replace('-', ' ', $eval['cognitive'])));
        $sheet->setCellValue('I' . $row, ucfirst(str_replace('-', ' ', $eval['psychomotor'])));
        $sheet->setCellValue('J' . $row, ucfirst(str_replace('-', ' ', $eval['affective'])));
        $sheet->setCellValue('K' . $row, $eval['comments'] ?? '');
        $sheet->setCellValue('L' . $row, date('Y-m-d', strtotime($eval['created_at'])));
        $sheet->setCellValue('M' . $row, $eval['teacher_fname'] ?? 'Unknown');

        $row++;
    }

    // Auto-size columns
    foreach (range('A', 'M') as $columnID) {
        $sheet->getColumnDimension($columnID)->setAutoSize(true);
    }

    // Set headers for download
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment;filename="Student_Evaluations_Export_' . date('Y-m-d_His') . '.xlsx"');
    header('Cache-Control: max-age=0');

    $writer = new Xlsx($spreadsheet);
    $writer->save('php://output');
    exit;
}

function exportToPDF($evaluations, $school, $search, $term, $rating, $class_id) {
    require_once '../TCPDF-main/TCPDF-main/tcpdf.php';

    class EvaluationExportPDF extends TCPDF {
        private $school;
        private $teacher_name;
        private $filters;

        public function __construct($school, $teacher_name, $filters) {
            parent::__construct();
            $this->school = $school;
            $this->teacher_name = $teacher_name;
            $this->filters = $filters;
        }

        public function Header() {
            // School logo
            if (!empty($this->school['school_logo']) && file_exists('../' . $this->school['school_logo'])) {
                $this->Image('../' . $this->school['school_logo'], 15, 10, 20, 20, '', '', '', false, 300, '', false, false, 0);
            }

            // School name and export info
            $this->SetFont('helvetica', 'B', 14);
            $this->SetXY(40, 12);
            $this->Cell(0, 6, strtoupper($this->school['school_name']), 0, 1, 'L');

            $this->SetFont('helvetica', '', 9);
            $this->SetXY(40, 18);
            $this->Cell(0, 4, 'Student Evaluations Export Report', 0, 1, 'L');

            $this->SetXY(40, 22);
            $this->Cell(0, 4, 'Generated by: ' . $this->teacher_name . ' | Date: ' . date('F j, Y'), 0, 1, 'L');

            // Filters
            $this->SetXY(40, 26);
            $filter_text = 'Filters: ' . implode(' | ', $this->filters);
            $this->Cell(0, 4, $filter_text, 0, 1, 'L');

            // Decorative line
            $this->SetLineWidth(0.5);
            $this->Line(15, 35, 195, 35);

            // Title
            $this->SetFont('helvetica', 'B', 12);
            $this->SetXY(15, 40);
            $this->Cell(0, 8, 'Student Evaluations Export', 0, 1, 'C');

            $this->SetY(55);
        }

        public function Footer() {
            $this->SetY(-20);
            $this->SetLineWidth(0.3);
            $this->Line(15, -18, 195, -18);
            $this->SetFont('helvetica', 'I', 8);
            $this->SetXY(15, -15);
            $this->Cell(0, 4, 'Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, 0, 'R');
        }
    }

    // Prepare filters for display
    $filter_info = [];
    if ($search) $filter_info[] = "Search: $search";
    if ($term) $filter_info[] = "Term: $term";
    if ($rating) $filter_info[] = "Rating: $rating";
    if ($class_id) {
        global $pdo;
        $stmt = $pdo->prepare("SELECT class_name FROM classes WHERE id = ?");
        $stmt->execute([$class_id]);
        $class_name = $stmt->fetchColumn();
        $filter_info[] = "Class: $class_name";
    }

    // Create PDF instance
    $pdf = new EvaluationExportPDF($school, $_SESSION['full_name'], $filter_info);

    // Set document information
    $pdf->SetCreator($school['school_name'] ?? 'School');
    $pdf->SetAuthor($school['school_name']);
    $pdf->SetTitle('Student Evaluations Export');
    $pdf->SetSubject('Student Evaluations Export Report');

    // Set margins
    $pdf->SetMargins(15, 55, 15);
    $pdf->SetHeaderMargin(5);
    $pdf->SetFooterMargin(25);
    $pdf->SetAutoPageBreak(TRUE, 30);

    // Add first page
    $pdf->AddPage();

    // Statistics
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->Cell(0, 10, 'Summary Statistics', 0, 1, 'L');
    $pdf->SetFont('helvetica', '', 9);

    $stats_text = "Total Evaluations: " . count($evaluations) . "\n";
    $stats_text .= "Unique Students: " . count(array_unique(array_column($evaluations, 'student_id'))) . "\n";
    $stats_text .= "Classes Covered: " . count(array_unique(array_column($evaluations, 'class_name'))) . "\n";
    $pdf->MultiCell(0, 5, $stats_text, 0, 'L');
    $pdf->Ln(5);

    // Data table
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->SetFillColor(240, 240, 240);

    // Table headers
    $headers = ['S/N', 'Student', 'Class', 'Term', 'Academic', 'Non-Acad', 'Cognitive', 'Psychomotor', 'Affective', 'Date'];
    $widths = [8, 35, 20, 12, 18, 18, 18, 18, 18, 20];

    foreach ($headers as $i => $header) {
        $pdf->Cell($widths[$i], 8, $header, 1, 0, 'C', true);
    }
    $pdf->Ln();

    // Table data
    $pdf->SetFont('helvetica', '', 8);
    $pdf->SetFillColor(248, 250, 252);
    $fill = false;

    $counter = 1;
    foreach ($evaluations as $eval) {
        $pdf->SetFillColor($fill ? 248 : 255, $fill ? 250 : 255, $fill ? 252 : 255);

        $pdf->Cell(8, 6, $counter++, 1, 0, 'C', $fill);
        
        // Student name (truncated)
        $name = strlen($eval['full_name']) > 18 ? substr($eval['full_name'], 0, 15) . '...' : $eval['full_name'];
        $pdf->Cell(35, 6, $name, 1, 0, 'L', $fill);
        
        $pdf->Cell(20, 6, $eval['class_name'], 1, 0, 'L', $fill);
        $pdf->Cell(12, 6, 'T' . $eval['term'], 1, 0, 'C', $fill);

        // Rating cells
        $ratings = ['academic', 'non_academic', 'cognitive', 'psychomotor', 'affective'];
        foreach ($ratings as $rating) {
            $rating_value = $eval[$rating];
            $pdf->Cell(18, 6, ucfirst(str_replace('-', ' ', $rating_value)), 1, 0, 'C', $fill);
        }

        $pdf->Cell(20, 6, date('Y-m-d', strtotime($eval['created_at'])), 1, 1, 'C', $fill);
        $fill = !$fill;
    }

    // Comments section if any
    $comments_exist = false;
    foreach ($evaluations as $eval) {
        if (!empty($eval['comments'])) {
            $comments_exist = true;
            break;
        }
    }

    if ($comments_exist) {
        $pdf->AddPage();
        $pdf->SetFont('helvetica', 'B', 11);
        $pdf->Cell(0, 10, 'Teacher Comments & Recommendations', 0, 1, 'L');

        $pdf->SetFont('helvetica', '', 8);
        $counter = 1;

        foreach ($evaluations as $eval) {
            if (!empty($eval['comments'])) {
                $pdf->SetFont('helvetica', 'B', 8);
                $pdf->Cell(0, 6, $counter . '. ' . $eval['full_name'] . ' (' . $eval['class_name'] . ')', 0, 1, 'L');

                $pdf->SetFont('helvetica', '', 7);
                $pdf->MultiCell(0, 4, $eval['comments'], 0, 'L');
                $pdf->Ln(2);
                $counter++;
            }
        }
    }

    // Generate filename and output
    $safe_teacher = preg_replace('/[^A-Za-z0-9\-_]/', '_', $_SESSION['full_name']);
    $filename = 'Student_Evaluations_Export_' . $safe_teacher . '_' . date('Ymd_His') . '.pdf';

    // Create directory if it doesn't exist
    $export_dir = dirname(__DIR__) . '/exports/evaluations/';
    if (!file_exists($export_dir)) {
        mkdir($export_dir, 0777, true);
    }

    $filepath = $export_dir . $filename;

    // Save PDF file
    $pdf->Output($filepath, 'F');

    // Log the export
    try {
        global $pdo;
        $stmt = $pdo->prepare("
            INSERT INTO export_logs (user_id, export_type, file_path, exported_at, ip_address)
            VALUES (?, 'evaluations_export', ?, NOW(), ?)
        ");
        $stmt->execute([
            $_SESSION['user_id'],
            $filepath,
            $_SERVER['REMOTE_ADDR'] ?? 'unknown'
        ]);
    } catch (PDOException $e) {
        // Silently skip logging if export_logs table doesn't exist
    }

    // Output PDF to browser
    header('Content-Type: application/pdf');
    header('Content-Disposition: inline; filename="' . $filename . '"');
    header('Content-Transfer-Encoding: binary');
    header('Accept-Ranges: bytes');
    header('Cache-Control: private');
    readfile($filepath);
    exit;
}
?>
