<?php
session_start();
require_once '../config/db.php';
require_once '../includes/functions.php';

// Allow principal and teacher
$role = $_SESSION['role'] ?? '';
if (!isset($_SESSION['user_id']) || !in_array($role, ['principal', 'teacher'], true)) {
    header("Location: ../index.php");
    exit;
}

$current_school_id = require_school_auth();

// Filters (support both admin and teacher pages)
$search = trim($_GET['search'] ?? '');
$filter_status = $_GET['filter_status'] ?? 'all';
$filter_grade = trim($_GET['filter_grade'] ?? '');
$filter_term = trim($_GET['filter_term'] ?? '');
$filter_class = trim($_GET['filter_class'] ?? '');
$filter_week = trim($_GET['filter_week'] ?? '');
$filter_subject = trim($_GET['filter_subject'] ?? '');

$query = "SELECT c.*, cl.class_name, u.full_name AS teacher_name
          FROM curriculum c
          LEFT JOIN classes cl ON c.class_id = cl.id AND cl.school_id = :school_id
          LEFT JOIN users u ON c.teacher_id = u.id AND u.school_id = :school_id
          WHERE c.school_id = :school_id_filter";

$params = [
    'school_id' => $current_school_id,
    'school_id_filter' => $current_school_id,
];

if ($role === 'teacher') {
    $query .= " AND (c.teacher_id = :teacher_id OR c.teacher_id IS NULL)";
    $params['teacher_id'] = $_SESSION['user_id'];
}

if ($filter_status !== '' && $filter_status !== 'all') {
    $query .= " AND c.status = :status";
    $params['status'] = $filter_status;
}

if ($search !== '') {
    $query .= " AND (c.subject_name LIKE :search OR c.grade_level LIKE :search OR c.description LIKE :search OR c.topics LIKE :search)";
    $params['search'] = '%' . $search . '%';
}

if ($filter_grade !== '') {
    $query .= " AND c.grade_level = :grade_level";
    $params['grade_level'] = $filter_grade;
}

if ($filter_term !== '' && $filter_term !== 'all') {
    $query .= " AND c.term = :term";
    $params['term'] = $filter_term;
}

if ($filter_class !== '' && $filter_class !== 'all') {
    $query .= " AND c.class_id = :class_id";
    $params['class_id'] = $filter_class;
}

if ($filter_week !== '' && $filter_week !== 'all') {
    $query .= " AND c.week = :week";
    $params['week'] = intval($filter_week);
}

if ($filter_subject !== '' && $filter_subject !== 'all') {
    $query .= " AND c.subject_id = :subject_id";
    $params['subject_id'] = intval($filter_subject);
}

$query .= " ORDER BY c.grade_level, c.term, c.week, c.subject_name";

$stmt = $pdo->prepare($query);
$stmt->execute($params);
$curriculums = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Fetch school profile for header
$stmt = $pdo->prepare("SELECT * FROM school_profile WHERE school_id = ? LIMIT 1");
$stmt->execute([$current_school_id]);
$school = $stmt->fetch(PDO::FETCH_ASSOC);

require_once '../TCPDF-main/TCPDF-main/tcpdf.php';

class CurriculumExportPDF extends TCPDF {
    private $school;
    private $generated_by;
    private $filters;

    public function __construct($school, $generated_by, $filters) {
        parent::__construct('L');
        $this->school = $school;
        $this->generated_by = $generated_by;
        $this->filters = $filters;
    }

    public function Header() {
        if (!empty($this->school['school_logo']) && file_exists('../' . $this->school['school_logo'])) {
            $this->Image('../' . $this->school['school_logo'], 15, 8, 20, 20, '', '', '', false, 300, '', false, false, 0);
        }

        $this->SetFont('helvetica', 'B', 14);
        $this->SetXY(40, 10);
        $this->Cell(0, 6, strtoupper($this->school['school_name'] ?? 'SAHABFORMMASTER'), 0, 1, 'L');

        $this->SetFont('helvetica', '', 9);
        $this->SetXY(40, 16);
        $this->Cell(0, 4, 'Curriculum Export Report', 0, 1, 'L');

        $this->SetXY(40, 20);
        $this->Cell(0, 4, 'Generated by: ' . $this->generated_by . ' | Date: ' . date('F j, Y'), 0, 1, 'L');

        $this->SetXY(40, 24);
        $this->Cell(0, 4, 'Filters: ' . implode(' | ', $this->filters), 0, 1, 'L');

        $this->SetLineWidth(0.4);
        $this->Line(15, 32, 282, 32);
        $this->SetY(38);
    }

    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('helvetica', 'I', 8);
        $this->Cell(0, 6, 'Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, 0, 'R');
    }
}

$filter_info = [];
if ($search) $filter_info[] = "Search: $search";
if ($filter_status && $filter_status !== 'all') $filter_info[] = "Status: $filter_status";
if ($filter_grade) $filter_info[] = "Grade: $filter_grade";
if ($filter_term) $filter_info[] = "Term: $filter_term";
if ($filter_week !== '' && $filter_week !== 'all') $filter_info[] = "Week: $filter_week";
if ($filter_class) {
    $stmt = $pdo->prepare("SELECT class_name FROM classes WHERE id = ? AND school_id = ?");
    $stmt->execute([$filter_class, $current_school_id]);
    $class_name = $stmt->fetchColumn();
    if ($class_name) $filter_info[] = "Class: $class_name";
}
if ($filter_subject) {
    $stmt = $pdo->prepare("SELECT subject_name FROM subjects WHERE id = ? AND school_id = ?");
    $stmt->execute([$filter_subject, $current_school_id]);
    $subject_name = $stmt->fetchColumn();
    if ($subject_name) $filter_info[] = "Subject: $subject_name";
}
if (empty($filter_info)) $filter_info[] = 'None';

$pdf = new CurriculumExportPDF($school, $_SESSION['full_name'] ?? 'Administrator', $filter_info);
$pdf->SetCreator($school['school_name'] ?? 'School');
$pdf->SetAuthor($school['school_name'] ?? 'School');
$pdf->SetTitle('Curriculum Export');
$pdf->SetSubject('Curriculum Export Report');

$pdf->SetMargins(15, 40, 15);
$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(15);
$pdf->SetAutoPageBreak(true, 20);
$pdf->AddPage();

// Summary
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell(0, 8, 'Summary', 0, 1, 'L');
$pdf->SetFont('helvetica', '', 9);
$pdf->MultiCell(0, 5, "Total Items: " . count($curriculums), 0, 'L');
$pdf->Ln(3);

// Table header
$pdf->SetFont('helvetica', 'B', 9);
$pdf->SetFillColor(240, 240, 240);
$headers = ['#', 'Subject', 'Grade', 'Term', 'Week', 'Class', 'Teacher', 'Status', 'Duration', 'Topics'];
$widths = [8, 38, 18, 18, 12, 30, 35, 18, 22, 60];

foreach ($headers as $i => $header) {
    $pdf->Cell($widths[$i], 8, $header, 1, 0, 'C', true);
}
$pdf->Ln();

$pdf->SetFont('helvetica', '', 8);
$fill = false;
$counter = 1;
foreach ($curriculums as $c) {
    $pdf->SetFillColor($fill ? 248 : 255, $fill ? 250 : 255, $fill ? 252 : 255);
    $pdf->Cell($widths[0], 6, $counter++, 1, 0, 'C', $fill);
    $subject = $c['subject_name'] ?? '';
    $pdf->Cell($widths[1], 6, mb_strimwidth($subject, 0, 25, '...'), 1, 0, 'L', $fill);
    $pdf->Cell($widths[2], 6, $c['grade_level'] ?? '-', 1, 0, 'C', $fill);
    $pdf->Cell($widths[3], 6, $c['term'] ?? '-', 1, 0, 'C', $fill);
    $pdf->Cell($widths[4], 6, ($c['week'] > 0 ? $c['week'] : '-'), 1, 0, 'C', $fill);
    $pdf->Cell($widths[5], 6, mb_strimwidth($c['class_name'] ?? '-', 0, 18, '...'), 1, 0, 'L', $fill);
    $pdf->Cell($widths[6], 6, mb_strimwidth($c['teacher_name'] ?? 'Unassigned', 0, 20, '...'), 1, 0, 'L', $fill);
    $pdf->Cell($widths[7], 6, ucfirst($c['status'] ?? ''), 1, 0, 'C', $fill);
    $pdf->Cell($widths[8], 6, $c['duration'] ?? '-', 1, 0, 'L', $fill);

    $topics_count = 0;
    if (!empty($c['topics'])) {
        $topics_count = count(array_filter(array_map('trim', explode("\n", $c['topics']))));
    }
    $pdf->Cell($widths[9], 6, $topics_count . ' topics', 1, 1, 'C', $fill);
    $fill = !$fill;
}

$safe_user = preg_replace('/[^A-Za-z0-9\-_]/', '_', $_SESSION['full_name'] ?? 'user');
$filename = 'Curriculum_Export_' . $safe_user . '_' . date('Ymd_His') . '.pdf';

// Output inline
header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename="' . $filename . '"');
header('Cache-Control: private');
$pdf->Output($filename, 'I');
exit;
